project:
  type: website

website:
  title: "Blue Sky Network"
  navbar:
    left:
      - href: index.qmd
        text: What is this?
      - href: pages/big-list.qmd
        text: The Big List
      - href: pages/big-plot.qmd
        text: The Big plot
      - href: about.qmd
        text: About
  page-footer: "Lasse Hjorth Madsen/Mike Young Academy" 

format:
  html:
    theme: cosmo
    css: styles.css