project:
  type: website

website:
  title: "Blue Sky Social"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: notes/keywords.qmd
        text: Keywords
  page-footer: "Lasse Hjorth Madsen/Mike Young Academy" 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true