project:
  type: website

website:
  title: "Scientists on Bluesky"
  navbar:
    left:
      - href: index.qmd
        text: What is this?
      - href: pages/big-list.qmd
        text: Influential Members 
      - href: pages/big-plot.qmd
        text: Network Visualisation
      - text: Notebooks
        menu:
        - href: notes/timeline.qmd
          text: Most recent network
        - href: notes/algorithm.qmd
          text: How the Algorithm Works
        - href: notes/compare.qmd
          text: Compare Networks
        - href: notes/explainer.qmd
          text: Centrality Explained
      - href: about.qmd
        text: About

  page-footer: "Lasse Hjorth Madsen/Mike Young Academy"
  google-analytics: "G-BYW6M5N4T9"

format:
  html:
    theme: cosmo
    css: styles.css