---
title: "Visualisation of Scientist Network on Bluesky"
format: html
toc: false
execute:
  echo: false
  warning: false
  cache: true
---

```{r packages}
#| cache: false
library(tidygraph)
library(igraph)
library(DT)
library(tidyverse)
library(RColorBrewer)
library(threejs)
library(htmlwidgets)

devtools::load_all(path = "../../blueskynet")
```

```{r load}
net <- readRDS("../data/clean_net_2024-02-03.rds")
profiles <- readRDS("../data/clean_profiles_2024-02-03.rds")
```

```{r compute}
graph <- read_rds("graph.rds")
edges <- graph |> activate(edges) |> as_tibble()
nodes <- graph |> activate(nodes) |> mutate(id = row_number()) |> as_tibble()

nodes <- nodes |>
  mutate(com_label = fct_infreq(as.character(community)),
         com_label = fct_lump(com_label, n = 10)) |>
  group_by(com_label) |>
  mutate(n = n(), com_id = cur_group_id()) |>
  ungroup() |>
  mutate(com_label = ifelse(com_id == max(com_id), "Other",
                            paste0(LETTERS[com_id], ", n=", n))) |>
  left_join(profiles, by = c("name" = "handle"))

# Make colors based on communities
community_cols <- 3 |> brewer.pal("Set1") |> colorRampPalette()
use_colors <- n_distinct(nodes$com_label) |> community_cols() |> sample()

nodes <- nodes |> mutate(color = use_colors[com_id], groupname = com_label)

# 3d plot with threejs
widget <- graphjs(graph, bg = "black",
                  vertex.size = 0.2,
                  edge.width = .3,
                  edge.alpha = .3,
                  vertex.color = nodes$color,
                  vertex.label = paste(nodes$displayName, nodes$description, sep = ": "))

rm(graph)  # Slows down Rstudio
```

This is a 3d-visualization of the scientists' network on Blue Sky Social. The plot is interactive, you can pan, zoom, rotate, using mouse or touch screen. Hovering over any individual will show their Blue Sky description. Perhaps go full-screen with F11. Have fun.
\
\

```{r}
#| column: screen
#| fig-height: 8
widget
```